#+title: General Introduction, second attempt
#+author: Falk Mielke

* Locomotion is Controlled Chaos
** Simple Chaos
A double pendulum can be a rather simple experimental arrangement.
Think of two metal bars, connected with a loose screw, and fixed to a holder (Fig. \ref{fig:pendulum}).
More generally, a double pendulum consists of two rigid bodies, which are coupled by a passive joint; the connection typically has between one and three rotational degrees of freedom.
The inertial properties (shape, mass distribution) are normally constant.
The pendulum would hang still, unless given an initial portion of kinetic or potential energy.

TODO: figure - image of a simple double pendulum/stick figure movement/chaos plot
#+LABEL: fig:pendulum

#+LABEL: def:kinematics
#+BEGIN_BOX
Kinematics: box definition
#+END_BOX


Despite its simplicity, even the most basic double pendulum can produce chaotic movement (Fig. \ref{fig:pendulum}).
"Chaotic" describes the fact that the trajectory of the components are non-repetitive, i.e. that we can extract no regular pattern when analyzing the kinematics (box \ref{def:kinematics}) of the system.
Although strictly speaking a physical pendulum is deterministic (i.e. observation should be identical with exactly identical conditions), in practice one will not observe the same trajectories repeatedly.
Chaos complicates efficient analysis of the system.
Single observations can be described or visualized, and when combining many different starting conditions, overview visualizations such as phase diagrams might show more or less stable attractors @@comment: TODO cite chaos literature@@.
However, unless analytical solutions of pendulum systems exist, it is usually complicated to establish causal relationship between (starting) conditions and observed movement.
Statistical comparisons of variations in the setup would be non-trivial.

TODO: figure - phase diagram or Lyapunov space of a pendulum attractor
#+LABEL: fig:chaos

To re-iterate: chaos emerges on a system as simple as a two-segment physical pendulum.

** The Biological Pendulum
A physical pendulum is not all too different from a limb - a limb being, per definition, an appendage of an animal which might have various functions.
The most relevant functions for this work are body support and locomotion.
Specifically, this thesis will be concerned with the movement of quadruped vertebrates @@comment: TODO: cite general anatomy@@.
In vertebrate limbs, segments are naturally defined by relatively rigid bony elements and their connective attachments (muscles, tendrons, etc.).
These are coupled by joints which have more or less degrees of freedom @@comment: TODO cite Armita@@.
Of course, the difference to a passive physical pendulum is that the muscles and joints act as motors and actuators @@comment: TODO what is an actuator?@@.
These motors are enabling and coordinating the aforementioned functions of the limb, support and locomotion.
To complicate things, these connective tissues violate the assumption of constant inertial properties and invoke more or less regular variation in shape and mass distribution (which is usually neglected).
But despite this, the familiar arrangement remains: a limb, as first approximation, can be described as a series of coupled rigid segments and joints.

Limbs can be considered as a "biological pendulum".


The constraining elements are joint degrees of freedom and connective attachments.
These critically influence the observed movements by restricting the configuration space (i.e. all possible spatial arrangements of segments).
In consequence, joint control and configuration space restriction "tame the chaos" and enable elegant analysis methods.


** Conventional Kinematic Analysis
Researchers have long recognized the regularity in locomotion and found clever ways of applying quantitative analysis.
- Muybridge: videos
- Bernstein: kinematograph

It quickly became apparent that the regularity is not perfectly regular: though periodic limb movement is far from being chaotic, considerable variation remains @@comment: TODO cite:Bernstein@@.

Locomotor control seems to reduce the system-inherent chaos to manageable variation.
