#+TITLE: Fourier Methods in the Quantitative Analysis\linebreak of Locomotor Kinematics and Coordination
#+SUBTITLE: -- a review, and a case study --
#+AUTHOR: Falk Mielke [[mailto:falkmielke.biology@mailbox.org][(falkmielke.biology@mailbox.org)]]
#+DATE: {{{time(%Y-%m-%d)}}}

#+SETUPFILE: org/latex_header.org

#+BIBLIOGRAPHY: literature.bib apalike
#+EXPORT_FILE_NAME: pt1ch2_fourieranalysis
#+OPTIONS: toc:nil

#+STARTUP: noinlineimages showeverything entitiespretty
#+ODT: <text:p text:style-name="PageBreak"/>

#+BEGIN_SRC emacs-lisp :exports none :results silent :tangle no
  (setq org-babel-inline-result-wrap "\\(%s\\)")
(setq bibtex-completion-bibliography
      '("./literature.bib"))
#+END_SRC

\clearpage
* Abstract
Analysis workflows which are based on the Fourier theorem are abundant in physics and engineering, yet rarely found in the biological literature.
They would be particularly useful in the analysis of locomotor kinematics, where movements can usually be broken down into repetitive cycles.
I herein repeat the basics of Fourier analysis and transformation to the frequency domain by reviewing previous studies which applied it in some form in the field of locomotor biomechanics.
I then discuss terminological and methodological heterogeneity among these studies, and point out some relevant properties of the method which have received relatively little attention.
One of the under-appreciated capabilities is that the transformation enables a diversity of multivariate analysis and modeling methods.
I demonstrate this by applying Fourier Series Decomposition, multivariate analysis and probabilistic modeling to a previously analyzed data set of bipedal walking kinematics in baboons.
The results are complementary to the prior analysis, and the capability to predict actual kinematic data for unobserved character combinations is of particular interest for future kinematics research.


@@latex:\FloatBarrier\clearpage@@
* Introduction
:PROPERTIES:
:CUSTOM_ID: intro12
:END:
#+INCLUDE: "02_intro.org" :minlevel 2

@@latex:\FloatBarrier\clearpage@@
* Fourier Series in Locomotor Research
:PROPERTIES:
:CUSTOM_ID: history
:END:
#+INCLUDE: "03_history.org" :minlevel 2

@@latex:\FloatBarrier\clearpage@@
* Properties of the Fourier Series
:PROPERTIES:
:CUSTOM_ID: properties
:END:
#+INCLUDE: "04_properties.org" :minlevel 2

@@latex:\FloatBarrier\clearpage@@
* Case Study: Predicting Bipedal Walking in Adult Male Baboons
:PROPERTIES:
:CUSTOM_ID: casestudy
:END:
#+INCLUDE: "05_casestudy.org" :minlevel 2

@@latex:\FloatBarrier\clearpage@@
* Summary
:PROPERTIES:
:CUSTOM_ID: summary
:END:
#+INCLUDE: "06_summary.org" :minlevel 2




@@latex:\FloatBarrier\clearpage@@
* Supplements
:PROPERTIES:
:CUSTOM_ID: appendix
:END:
#+INCLUDE: "09_appendix.org" :minlevel 2

# no title/section on the references
# \bibliographystyle{org/apalike}
# \bibliography{literature.bib}


#+BEGIN_COMMENT
TODO:
### For MS:
    + Abstract

### For Thesis:
    + info boxes
      + "collective variables"
      + "configuration"
#+END_COMMENT
