#+TITLE: The "Flying Femur"
#+SUBTITLE: Computed Tomography and the Potential Facilitation of Inverse Dynamic Calculations
#+AUTHOR: Falk Mielke
#+DATE: <2023-03-07 Thu>

#+SETUPFILE: latex_header.org
#+EXPORT_FILE_NAME: pt3ch6_dynamics

#+BIBLIOGRAPHY: literature.bib apalike
#+BEGIN_SRC elisp :results none :exports none :tangle no
(setq bibtex-completion-bibliography
      '("literature.bib"))
#+END_SRC

#+OPTIONS: toc:t

#+STARTUP: noinlineimges showeverything entitiespretty
@@latex:\clearpage@@
#+ODT: <text:p text:style-name="PageBreak"/>


* Abstract
Here, I am going to write a summary of this extraordinary manuscript.

@@latex:\clearpage@@

* Introduction
Until this point, this thesis has been busy with methodological development in terms of measuring kinematics.
With Fourier-based methods and probabilistic models in place, one can
  (i) quantify measured kinematics
  (ii) simulate locomotion by predictive sampling of trained models.
This is a full grasp at *how limb segments of animals change their position in space*.
Segments could be axial or peripheral parts of the animal which move as a unit (rigid- or pseudo-rigid bodies).


Another aspect of locomotion is *why segments move*.
This opens up the rabbit hole of elementary physics:
#+begin_quote
A rigid body will change its linear or angular momentum if there are external forces or external torques applied to it.
#+end_quote
This is also called the *Conservation of Momentum*.
And the study of the conservation of momentum in moving rigid body systems is called "Dynamics", which is the topic of this third part of the thesis.
Again, this will contain methodological considerations, backed up with actual measurements of (at least a part of) a piglet.


In a nutshell:
+ Wrenches and quaternions are a useful computational tools for calculating rigid body dynamic models.
+ Balance Equations are the mathematical manifestation of conservation of momentum.
+ Reference frame considerations can simplify calculations; however, only static frame calculations result in correct joint moments.
+ Fictitious Forces are unbalanced change of momentum. If one intends to calculate balances in an accelerating frame, include four fictitious forces: D’Alambert, Euler, Coriolis, and the Centrifugal force.
+ Computed Tomography might be a shortcut to approximate material constants which are crucial for the calculation of dynamics.


Again, a lot of the herein summarized work is physics textbook knowledge, re-formulated to be more readily applied to animal locomotion.
Again, the premise for the presented work was "falsification": for example, instead of assuming that CT scan data is useful to easily extract inertial properties of body segments, this strategy attempts to find flaws in that procedure.

Yet prior to being able to judge a procedure, it is necessary to describe it.
I will therefore start by summarizing the theory behind Inverse Dynamics, pointing at sources and conventions that turned out to be useful for the present research.

* Dynamics: Theory
** Balance of Forces and Moments
When constructing a robot with motors and actuators at the joints, the default problem is to set the appropriate joint torques to generate a desired movement.
This is called the forward problem citep:Lynch2017.
Conversely, *inverse dynamics* describes the calculation of joint moments which were necessary to generate an observed movement.
The study of animal locomotion is mostly concerned with the inverse situation.


The central units herein are forces and "moments", the latter being a physical quantity related to forces.
Forces are the product of mass and an acceleration, \(F=ma\), one of Newton's laws of motion.
In fact, force is better expressed as the temporal change of linear momentum \(p\), hence \(F=\frac{d p}{d t}\) (total derivative).
Linear momentum is defined as follows: \(p=m\dot x\), with \(m\) the mass and \(\dot x\) the linear velocity (change of position over time).

Let us fill this in and apply the total derivative:
#+begin_center
\(\frac{dp}{dt} = m \cdot \frac{\partial \dot x}{\partial t} + \frac{\partial m}{\partial t} \cdot \dot x\)
#+end_center

We can apply the inverted version of the mathematical "chain rule" (hence: "unchain rule"):
#+begin_center
\(\frac{\partial m}{\partial t} = \frac{\partial m}{\partial x} \cdot \frac{\partial x}{\partial t} \)
#+end_center

Which, plugged back into the change of linear momentum, gives the complete force formula.
@@latex:\label{eqn:force}@@
#+begin_center
\[F = m \cdot \ddot x + \frac{\partial m}{\partial x} \cdot \dot x \dot x \]
#+end_center


Because \(a=\ddot x\), the first part of the RHS expression in equation @@latex:\eqref{eqn:force}@@ is the familiar \(F=ma\).
The second part is more enigmatic: those are "velocity product terms", i.e. the partial derivatives of the mass matrix, accounting e.g. for configuration changes of a chain of segments.
Assuming here that mass distribution of single segments is constant (which is generally an inaccurate simplifying assumption), I will neglect that part.

Hence, we get a more or less familiar equation for the Force \(F\), which tells us that the change in linear momentum (\(ma\)) must be equal to a (external) force.
\(F\) is a three element vector.


Mass is therein the resistance of an object to linear acceleration, i.e. to change of linear momentum \(p\).
Analogously, Mass Moment of Inertia (\(I\)) is the resistance of an object to rotational acceleration, which induces a change in angular momentum \(M\).
And so, the series of equations above can be applied analogously to angular momentum \(L\) (with angular velocity \(\dot \omega\)).


The time derivative is as follows.
#+begin_center
\(\frac{dL}{dt} = I \cdot \frac{\partial \dot \omega}{\partial t} + \frac{\partial I}{\partial t} \cdot \dot \omega\)
#+end_center


And with further manipulation citep:Widnall2009 we get:
#+begin_center
\(M = I \ddot\omega + \dot\omega \times I\dot\omega \)
#+end_center

Again, there is an (angular) velocity product term which we hope to sufficiently well approximate by setting it to zero.
And, just as in the linear case, we identify a cause for any change in angular momentum, and call it the moment.
There is one extra step, however: the momentum requires a reference point, and it changes depending on which point is chosen.


The analogy above is no coincidence.
Force is a 3D vector.
Moment is a 3D vector with a reference point.
And Moments are in fact just Forces acting at a lever.


On top of the Force/Moment complexity comes the issue of rotation in space.
Angular momentum depends on angular acceleration, which is the temporal derivative of "angle".
But getting that angle in 3D is not exactly trivial, and there are several complementary notations.

Conventions, conventions, conventions: to guide my readers towards the actual application of all this, the following paragraphs will summarize the conventions I found most useful to perform inverse dynamic calculations in an XROMM setting.


** Screw Theory and Wrenches
There is a framework to unify the components of momentum, which is called *Screw Theory* citep:Dumas2004,Lynch2017.

The trick here is to concatenate the vectors \(F\) and \(M\) to form a six element vector \(W\), *the Wrench* (Fig. \ref{fig:wrench}, cf. https://en.wikipedia.org/wiki/Screw_theory).
"6D" might seem unhandy, and one may ask "why".
The answer is computational convenience citep:Dumas2004: the wrench saves us from double computation, by linking the two parts of momentum.

#+CAPTION: A Wrench is a combined vector of force and moment, consisting of six elements, and requiring a point of application. Wrench vectors are depicted as arrows, yet in contrast to forces, their tim points towards the point of application. Note that this is actually a 3D sketch, yet the limitations of a printed PhD thesis prohibit illustration beyond the paper plane projection.
#+LABEL: fig:wrench
#+ATTR_LATEX: :width 6cm
[[./figures/the_wrench.pdf]]

# Dumas 2004, Lynch and Park 2017
# http://mielke-bio.info/falk/posts/10.id_lmx0a_wrenches


** Quaternions
When we think about rotation in space, we might think about an axis and an angle.
And that is a good point to start.

#+begin_center
axis: \(\begin{pmatrix}x\\y\\z \end{pmatrix}\), angle: \(\theta\)
#+end_center

Ideally, one would want to combine those into a single object \(q\), and it turns out that the following way is convenient:

@@latex:\label{eqn:quaternion}@@
#+begin_center
\[\begin{pmatrix}cos(\theta/2)\\x\cdot sin(\theta/2)\\y\cdot sin(\theta/2)\\z\cdot sin(\theta/2) \end{pmatrix} = q = \begin{pmatrix}q_w\\q_x\\q_y\\q_z \end{pmatrix}\]
#+end_center

There also exists a conjugate, \(q^{-1}\):
#+begin_center
\[q^{-1} = (q_w, -q_x, -q_y, -q_z)\]
#+end_center


And this object allows for convenient spatial rotation, by almost-simple multiplication:
take any point \(P\) with coordinates \(0, a, b, c\):
#+begin_center
\[P_{rot} = q\cdot P\cdot q^{-1}\]
#+end_center

Most computational tools can handle this operation quickly and efficiently.
Better yet, one can stack quaternions by (non-commutatively) multiplying them:
#+begin_center
\[ q_2 \cdot \left( q_1\cdot P\cdot q_1^{-1}\right) \cdot q_2^{-1} = (q_1\cdot q_2) P (q_1\cdot q_2)^{-1} \]
#+end_center

Also, working with time series of quaternions (\(q(t)\)), there is a formula for getting the angular velocity from the time differences \(dq/dt\).
#+begin_center
\[\omega = 2 \frac{dq}{dt} \cdot q^{-1} \]
#+end_center


Most of these formulas are included as functions in common quaternion toolboxes (for example in [[https://www.mathworks.com/discovery/quaternion.html][matlab]], [[https://cran.r-project.org/web/packages/onion/onion.pdf][R]], and [[https://pypi.org/project/numpy-quaternion][Python]]).
And those also enable the conversion to other notations of spatial rotation (Euler- or Tait-Bryan angles, Rotation Matrices).

    # http://www.euclideanspace.com/physics/kinematics/angularvelocity/QuaternionDifferentiation2.pdf


** Computational Convenience
citep:Dumas2004

** Balance of Wrenches
 conservation of linear and angular momentum
 + FJ=mx¨+∂m∂xx˙x˙=mx¨
 + MJ=Iω¨+ω˙×Iω˙


** Mass Moment of Inertia
resistance to angular acceleration
Vector formula
Generalized Steiner
*** Conventional Methods
*** Using CT scans
citep:DuPlessis2013,Durston2022

** Reference Frames and Ficticious Forces
 Take home message: Make sure, in this and all that follows, in what reference frame parameters are defined and whether they were transformed.
 # http://mielke-bio.info/falk/posts/11.id_lmx0b_fforces/

 D’Alambert Force, Euler force, Centrifugal force, Coriolis force

 # http://mielke-bio.info/falk/posts/15.id_lmx4_arm/
 After all, this is how physicists formalize fictitious forces: I read that when Léon Foucault observed precession of his pendulum, no responsible external force could be found, but angular momentum of the pendulum changed. Coriolis Force rectified this discrepancy, and because Coriolis force comes with a rotating frame, this was evidence for the rotation of the earth.

 Back to our question. Are there more than the four fictitious forces? Probably no. Remember the “five accelerations” derivation linked in the prequel notebook of this series. That derivation captures all the possible forms of momentum for which we have evidence.


 I have encountered several types of definitions of fictitious forces during my initial attempts.

 The first type is a practical one, which goes along the lines of “fictitious forces arise because an observer who is captured in the rotating frame is blind to the movement of the frame”. Yes, that is a valid description, but a disappointing definition: What else might the observer be blind to? How can we calculate something we are blind for? And why can’t I not always switch perspective in cases where I’m in charge of the data?

 The second type of definition is a technical one: “fictitious forces need to be introduced to make balance equations work in the rotating reference frame”. That is also a valid point, yet it leaves similar questions as above: Which ones do I have to include when? Where do the formulas come from?

 I have hinted at these aspects above. They certainly help to develop an intuition about fictitious forces, but for me they were not satisfactory. You can find these two categories scattered all over the Wikipedia articles about fictitious forces. Despite my rants herein, I’m not disappointed about Wikipedia, it is just sad that this confirmed my prior on that “Encyclopedia”. But I also see myself as a source of the problem: whereas for trained physicists it is often obvious which and how vectors add up, my humble, untrained mind needs some more explicit guidance. [update 2020/09/12] And although I’m using myself in a tautologous way here, those of you who read my first version of the notebook are witness that I could confidently ignore the D’Alambert force without noticing.

 I found a third definition most convincing, yet it is more like a prescription than a definition. It is the one which I found in the workbooks by Frank Owen (five-term acceleration, see references).

     Conceive a position vector to a point on a rigid body as a superimposition of the position vector of the reference frame attachment point (in static frame), and the movement of the point of interest relative to the attachment (in body frame).
     Calculate component-wise time derivatives of that superimposed vector; use product rule, and make sure to incorporate time changes of reference frame basis vectors.
     In the outcome, two acceleration components are intuitive cartesian superimpositions; the others depend on cross products of angular and linear motion parameters. Four of them are irritatingly labelled “fictitious”.
     A corollary rule of thumb for those three: angular motion parameters (ω

 and derivatives) stem from the static frame, whereas linear motion parameters (x

     and derivatives) are best seen in the body frame.

 [update 2020/09/12] Finally, after having finished my work on this series of notebooks, I would like to attempt another definition, which I think captures the inverse dynamics standpoint: Instead of being forces, Fictitious Forces represent a change of the momentum which is not captured by kinematics in the observer’s frame of reference. Instead of writing them on the side of the external forces (of which I think as the cause of a momentum change), I tend to put them on the “effect” side and would rather call them “unbalanced change of momentum” (“unbalanced” as in “not part of the balance”).

 I had to write a couple of notebooks to come to that conclusion, and would be glad if you like to follow through. The fourth one will explain this fourth definition in more detail.

 This preparational notebook has solved some puzzles which I encountered when starting to learn about fictitious forces. Make sure to keep track of your reference frames and reference points. Good (i.e. explicit, structured, well commented) programming style can facilitate this. And remember that, even if you think it is obvious which parameters you took in which transformation, make sure that others can reproduce your line of thought.

 With these tools at our hands, we can advance to elementary examples. I’ll start by isolating Euler, i.e. with an example that should show the Euler force in isolation, in the next notebook. If you don’t mind the explanations, feel free to skip ahead to the code from the application to a general (n-link) limb.


** Application: The N-Segment Piglet Limb
# http://mielke-bio.info/falk/posts/16.id_lmx5_nlink

* Results
** Issue 1: Beam Hardening
** Issue 2: Chemical Composition
+ water streaks on the scan
** Issue 3: Marker Artifacts
+ helical scanning

* Discussion
** Which Inertia Component is Relevant?


* Acknowledgements
# Joaquim & VisionLab
tbd.

# \pagebreak
# References
# \bibliographystyle{apalike}
# \bibliography{literature.bib}
