#+TITLE: Inverse Dynamics: A Methodological Overview
#+AUTHOR: Falk Mielke
#+DATE: <2023-03-07 Thu>

#+SETUPFILE: latex_header.org
#+EXPORT_FILE_NAME: pt3ch6_dynamics

#+BIBLIOGRAPHY: literature.bib apalike
#+BEGIN_SRC elisp :results none :exports none :tangle no
(setq bibtex-completion-bibliography
      '("literature.bib"))
#+END_SRC

#+OPTIONS: toc:t

#+STARTUP: noinlineimges showeverything entitiespretty
@@latex:\clearpage@@
#+ODT: <text:p text:style-name="PageBreak"/>


* Abstract
This thesis has so far explored the measurement and modeling of movement of terrestially locomotion.
A topic which remains to be discussed is the /cause/ of that movement.
The segments of animal limbs can be modeled as rigid bodies, each of which has a specific momentum.
Momentum is a conservative quantity, i.e. it changes due to energy transfer with its surrounding.
The retrospective inference of reasons for momentum change is often labeled "inverse dynamics".

The field of (inverse) dynamics is subject to various conventions and some methodological flexibility.
The purpose of this chapter is to set the table and clarify conventions used in this thesis.
The physical fundamentals and general algorithm applied in inverse dynamics calculations is presented, as well as elegant mathematical tools to implement it (wrenches, quaternions).
To illustrate the basic principles of physics which come to play in this chapter, a hypothetical collision experiment is discussed.
It turns out that, whereas most quantities in inverse dynamic calculations can be accurately measured, the inertial properties of segments are the achilles heel of accurate dynamic modeling.


@@latex:\clearpage@@

#+CAPTION: A hypothetical, scientific experiment to illustrate dynamic modeling (see text). Upper left: experimenter setting a door in motion. Lower right: subject running towards the experimental setup.
#+LABEL: fig:slamming
#+ATTR_LATEX: :width 12cm
[[./figures/slamming_door.pdf]]


* Introduction
** A Momentum Experiment
"Slamming a door in someone's face" is not a friendly thing to do.
Yet "friendliness" is not a scientific category, and thus we must consider this as a purely physical process (Fig. \ref{fig:slamming}).
If a person in question is running at constant velocity (which we could quantify using Fourier methods and probabilistic modeling, see before), the unexpected appearance of an obstacle will certainly force the subject to change trajectory.
If the unfortunate subject is unable to adjust on time, physicists would call this a "collision experiment".
In most probable cases the impact will thus *change the subject's momentum*.
The non-sliding door itself, set up on a hinge (point \(P\) in Fig. \ref{fig:slamming}), will gain rotational momentum through the act of slamming, performed by an experimenter.
In the collision case, the subject might (i) decelerate but proceed, (ii) come to a hold, or (iii) ungently bounce backwards from the elastic collision.
The door will thus transfer inertia to the subject, thereby ultimately canceling out (part of) the inertia of the person if the impact is in opposite direction and approximately equal magnitude to the running.
Trained experimenters might even succeed in (iv) transferring angular momentum to the surprised subject, generating a spin (though attention must be paid to whether that spin is partially caused by an evasive motor response of the subject).
All these possible outcomes are manifestation of the *conservation of energy and momentum*, which we will explore in detail below, using the hypothetical door slamming experiment as a metaphor.
Due to the numerous involved variables, it is not clear /a priori/ how exactly a subject will be hit, and what the exact consequences of the collision are.
Predicting the outcome of such scientific experiments is enabled by a major field of biomechanics which is called *dynamic modeling*.


** Kinematics and Kinetics
In the next chapter \ref{TODO}, I will discuss a specific contribution to dynamic modeling, namely the extraction of inertial properties from CT scans.
Prior to that, the question of "why we would need that" (i.e. CT scan analysis) has to be addressed by illustrating the overall context.
Establishing the connection to the previous topics of this thesis is impossible without a superficial overview of the dynamic modeling technique.
By providing such an overview in the following paragraphs, I hope to enable the reader to better understand the purpose and meaning of the specific contribution of the next chapter.
Experienced biomechanicists who are also familiar with "screw theory" are welcome to skip to the next chapter.


Until this point, this thesis has been busy with methodological development in terms of measuring, modeling and predicting /kinematics/.
With Fourier-based methods and probabilistic models in place, one can
  (i) quantify measured kinematics
  (ii) simulate locomotion by predictive sampling of trained models.
This is a complete quantification of /how/ limb segments of animals change their position in space.
Segments could be axial or peripheral parts of the animal which move as a unit (rigid- or pseudo-rigid bodies, hence the general term "rigid body dynamics"), which is to a large extent analogous to a door on a hinge.

Having cleared the /how/ in previous chapters, the other relevant aspect of locomotion is /why/ segments move.
This opens up the rabbit hole of elementary physics:
#+begin_quote
A rigid body will change its linear or angular momentum if there are external forces or external torques applied to it.
#+end_quote
This, again, is a formulation of the conservation of momentum, as introduced above.

These things seem quite intuitive: the slamming door will affect the subject upon impact.
And because there must be movement before or after the event of interest, and because that movement changes (i.e. it is "dynamic"), the study of the conservation of momentum in moving rigid body systems is called "dynamics".
In contrast to kinematics, dynamics are sometimes also called "kinetics", the study of motion and its causes.
"Conservation" as it is understood in physics implies that the measure of interest (momentum) cannot be created or lost, only gets converted to another form or transferred to another object.
Thus, dynamics are also linked to the calculation of transformations and transfers of energy from one form to another.
These conversions and transformations are precisely the reason /why segments or subjects change their movement/, and we seek to quantify and model (i.e. predict) them.


In applied terms, which algorithm or technique would we apply to quantify and model such an abstract thing as "momentum"?
There are many, all useful under different circumstances.
I will present herein the methods which seemed most useful and intuitive to me, and I will explain "why".
Yet this does not imply that they are generally preferred by all experts in the field.
# (rather the contrary: they lack acceptance, despite their usefulness, which I hope to change by kindling understanding)
In a nutshell:
+ Wrenches and quaternions are a useful computational tools for calculating rigid body dynamic models.
+ Balance Equations are the mathematical manifestation of conservation of momentum.
+ Reference frame considerations can simplify calculations; however, only static frame calculations result in correct joint moments.
+ Fictitious Forces are unbalanced change of momentum. If one intends to calculate balances in an accelerating frame, include four fictitious forces: D’Alambert, Euler, Coriolis, and the Centrifugal force.
+ Computed Tomography might be a shortcut to approximate material constants which are crucial for the calculation of dynamics (next chapter).


Once more, the herein summarized work is physics textbook knowledge, re-formulated to be more readily applied by the author to animal locomotion; as mentioned above, I consider this necessary context.
# And once more, the premise for the presented work was "falsification": for example, instead of assuming that CT scan data is useful to easily extract inertial properties of body segments, this strategy attempts to find flaws in that procedure.
This chapter will summarize the theory behind inverse dynamics, and point at literature references and conventions which turned out to be useful for the purpose of this thesis.


* Dynamics: Theory
** Forward and Inverse Problems
Since the "slamming door" experiment (Fig. \ref{fig:slamming}) could be unpleasant for the faces of living subjects, one might be tempted to measure on a robot.

When constructing a robot with motors and actuators at the joints, the first problem is to set the appropriate joint torques to generate a desired movement.
This is called the forward problem citep:Lynch2017.
Conversely, *inverse dynamics* is a second problem which describes the inference of joint moments which could have possibly generated an observed movement.
For example, from observing (i.e. measuring) a hinge door moving at a certain angular velocity, we can calculate the force and moment the experimentor has applied previously to set it in motion.
The study of animal locomotion is mostly concerned with this second, inverse situation.
The central quantities are "forces" and "moments", the latter being a physical quantity related to forces and involved in rotational movement.
We will approach forces and moments separately, before joining them in a common framework.


** Forces
Forces are the product of mass and an acceleration, \(F=m\ddot x\), one of Newton's laws of motion citep:Newton1687,Tipler2007.
In fact, force is better expressed as the temporal change of linear momentum \(p\), hence \(F=\frac{d p}{d t}\) (total derivative).
Linear momentum is defined as follows: \(p=m\dot x\), with \(m\) the mass and \(\dot x\) the linear velocity (change of position over time).

Combining these equations and applying the total derivative:
#+begin_center
\(\frac{dp}{dt} = m \cdot \frac{\partial \dot x}{\partial t} + \frac{\partial m}{\partial t} \cdot \dot x\)
#+end_center

We can apply the inverted version of the mathematical "chain rule" (hence: "unchain rule"):
#+begin_center
\(\frac{\partial m}{\partial t} = \frac{\partial m}{\partial x} \cdot \frac{\partial x}{\partial t} \)
#+end_center

Which, plugged back into the change of linear momentum, gives the complete force formula.
@@latex:\label{eqn:force}@@
#+begin_center
\[F = m \cdot \ddot x + \frac{\partial m}{\partial x} \cdot \dot x \dot x \]
#+end_center


Because \(a=\ddot x\), the first part of the RHS expression in equation @@latex:\eqref{eqn:force}@@ is the familiar \(F=ma\).
The second part is more enigmatic: those are "velocity product terms", i.e. the partial derivatives of the mass matrix, accounting e.g. for configuration changes of a chain of segments.
Assuming here that mass distribution of single segments is constant (which is generally an inaccurate simplifying assumption), I will neglect that part.

Hence, we get a more or less familiar equation for the Force \(F\), which tells us that the change in linear momentum (\(m\ddot x\)) must be equal to a (external) force.
\(F\) is a three element vector.


** Moments

#+CAPTION: Force and Moment. A force applied further away from the hinge \(P\) (situation A) will generate a larger momentum than a force similar in magnitude, but applied more proximal to the hinge (situation B). The reason is that the moment is defined as the vector cross product of the position vector of the force application point (in a hinge-centered reference frame) and the force vector.
#+LABEL: fig:slamming_moment
#+ATTR_LATEX: :width 12cm
[[./figures/slamming_shift.pdf]]

In the door slamming experiment, and experimenter must apply force to the door in order for the experiment to "succeed".
Yet the movement of the door depends on where the force is applied (Fig. \ref{fig:slamming_moment}).
Consider slamming a door by applying a force close to the hinge.
This either requires much higher force, or yields much less spectacular experimental outcomes than applying force to the distal side of the door (furthest from hinge, e.g. at the handle).
In fact, this simple physical observation explains why doors have evolved handles in the place where we observe them in extant doors.


Otherwise, the calculation of angular quantities is largely analogous to the linear case citep:Lewin801L20,Tipler2007.
Mass, in the force equation, is the resistance of an object to linear acceleration, i.e. to change of linear momentum \(p\).
Analogously, Mass Moment of Inertia (\(I\)) is the resistance of an object to rotational acceleration, which induces a change in angular momentum \(L\).
From experience, we can tell that lifting a door out of its hinge is a different process than conventionally rotating it, thought few have carried out this comparison in the absence of gravitation and friction.
And so, the series of equations above can be applied analogously to angular momentum \(L\) (with angular velocity \(\dot \theta\)).

#+begin_center
\(L = I \dot \theta\)
#+end_center

The time derivative is as follows.
#+begin_center
\(\frac{dL}{dt} = I \cdot \frac{\partial \dot \theta}{\partial t} + \frac{\partial I}{\partial t} \cdot \dot \theta\)
#+end_center

The change of angular momentum is called moment (\(M\)), and with further manipulation citep:Widnall2009 we get:
@@latex:\label{eqn:moment}@@
#+begin_center
\[M = I \ddot\theta + \dot\theta \times I\dot\theta \]
#+end_center


#+CAPTION:
#+LABEL: fig:slamming_momentum
#+ATTR_LATEX: :width 12cm
[[./figures/slamming_momentum.pdf]]

Again, there is an (angular) velocity product term which we hope to sufficiently well approximate by setting it to zero.
Just as in the linear case, we identify a cause for any change in angular momentum, and call it the moment \(M\) (others may call it torque \(\tau\)).
However, there is one extra step: calculation of the *angular momentum requires a reference point* (usually the hinge, \(P\), as above, but any point could be chosen).
The calculated angular momentum actually changes depending on which reference point is chosen.
Returning to the example of the door, rotating on a hinge (Fig. \ref{fig:slamming_momentum}).
We can approximate the door by a point mass in point \(D\).
Angular momentum \(L\) relative to point \(P\), which we denote \(L_P\), is calculated by using the cross product of the vector from point \(P\) to \(D\) (\(r_{PD}\)) and the linear momentum \(p=mv\):
#+begin_center
\(L_{P} = r_{PD} \times p = m r_{PD} \times v \)
#+end_center
From cross product properties, we see that the direction of \(L\) does not change during the slamming (stays parallel to the hinge axis), and the magnitude stays constant and greater than zero if velocity is greater than zero.

In contrast, the point mass door has a different angular momentum when calculating it relative to point \(D\): the position vector \(r_DD\) becomes zero, so \(L_{D} = 0\) at all times.
This is non-intuitive: the door rotates, after all; yet remember that we are reducing it to a point mass here and \(L_{D} = 0\) only holds for the point mass case!
Other points and non-pointmass-objects require more complex calculations, except maybe in the special case where rotation happens about the center of mass (\(COM\)).
In this special case, we speak of "spin angular momentum", which is an intrinsic property of the object in a sense that we do not need to give a reference point any more because everyone knows that the \(COM\) is the reference point for spin angular momentum.
# https://www.youtube.com/watch?v=sNaaL19opxw


But the general idea is that one needs to keep track of a reference point for angular momentum, and thus also for all changes in angular momentum.


** Screw Theory and Wrenches

The formulas for force and moment above resemble.
In fact, a common trick to help novice physicists remember the angular formulas is to replace position \(x\) by \(\theta\) (and derivatives accordingly), and mass \(m\) by mass moment of inertia \(I\) citep:Tipler2007.

The force-moment-analogy is no coincidence.
Force is a 3D vector, acting at a point.
Moment is a 3D vector with a reference point.
The moment is in fact just the corresponding force acting at a lever.
And the lever is usually the same position vector used to calculate angular momentum; in other words, given that we stay in the same reference frame, we might just need the force and the reference point and the moment follows.

Would it not be useful then to join force and moment?


It would.
There is a framework to unify the linear and angular components of momentum, which is called *Screw Theory* citep:Ball1876,Lynch2017.

The trick is to concatenate the vectors \(F\) and \(M\) to form a six element vector \(W\), *the Wrench* (Fig. \ref{fig:wrench}, cf. https://en.wikipedia.org/wiki/Screw_theory).
"6D" might seem unhandy, and one may ask "why".
The pure and simple answer is computational convenience citep:Dumas2004,Mueller2018: the wrench saves us from double computation, by linking the two intrinsically related parts of momentum.

#+CAPTION: A Wrench is a combined vector of force and moment, consisting of six elements, and requiring a point of application. Wrench vectors are depicted as arrows, yet in contrast to forces, their tip points towards the point of application (they can be moved around, adjusting the moment component; see text). Note that this figure is actually a 3D sketch, yet the limitations of a printed PhD thesis prohibit illustration beyond the paper plane projection.
#+LABEL: fig:wrench
#+ATTR_LATEX: :width 6cm
[[./figures/the_wrench.pdf]]


Any modern scripting language used to solve inverse dynamic questions can easily work on six element arrays/vectors instead of three-dimensional ones.
A mathematical shorthand for writing wrenches are square brackets and a semicolon indicating that the (column vector) components are concatenated (to form a longer column vector):
#+begin_center
\(W = \left[ F; M \right]\)
#+end_center

#+CAPTION: The door slamming experiment in wrench notation (see text). Point \(P\) is the origin of the reference frame, \(r_{PD}\) is the position vector to the attack point \(D\) of the wrench \(W\).
#+LABEL: fig:slamming_wrench
#+ATTR_LATEX: :width 12cm
[[./figures/slamming_wrench.pdf]]


** Balance of Wrenches
Plugging in equations \eqref{eqn:force} and \eqref{eqn:moment} from above, we get an expression for what can be referred to as the *dynamic wrench*:
@@latex:\label{eqn:dynamic_wrench}@@
#+begin_center
\[W_{dyn} = \left[ m\ddot x; I\ddot \theta \right]\]
#+end_center

Wrenches can be added up, for example the dynamic wrench can be easily shifted (vector \(s\)) to a different reference point, which does not require extra adjustment of the mass moment of inertia:
@@latex:\label{eqn:shift_wrench}@@
#+begin_center
\[\bar W_{dyn} = W_{dyn} + \left[ 0; s \times F \right]\]
#+end_center


The \(x\) and \(theta\) in the dynamic wrench refer to the movement of the rigid body itself and are immediately derived from the object's kinematics.
The inertial properties \(m\) and \(I\) have to be measured or approximated separately (see below).
The dynamic wrench expresses the total change of momentum of an object.


On the other hand, we have any *external wrenches* acting on the object.
The most important ones are the gravitational wrench, friction wrench, and the tip wrench.
#+begin_center
\(W_{g} = \left[ mg; 0 \right]\)
#+end_center
#+begin_center
\(W_{f} \approx \left[ 0; 0 \right]\)
#+end_center
#+begin_center
\(W_{tip}_{} = \left[ F_{tip}; M_{tip} \right]\)
#+end_center

We can sum up all external wrenches to get a total external wrench \(W_{ext}\):
@@latex:\label{eqn:external_wrench}@@
#+begin_center
\[W_{ext} = \sum\limits_{ext} W_{i} = W_{tip}+W_{g}+W_{f}+\ldots\]
#+end_center

Any other known external forces and moments should be added in wrench form.


Equations \eqref{eqn:dynamic_wrench} and \eqref{eqn:external_wrench} constitute the *Balance of Wrenches*:
@@latex:\label{eqn:balance_of_wrenches}@@
#+begin_center
\[W_{dyn} = \sum\limits_{ext} W_{i} \]
#+end_center

In other words:
#+begin_center
The change of [linear;angular] momentum of a rigid body is equal to the sum of external wrenches acting on it.
#+end_center


** Reference Frames

For simplicity, I ignored the issue of reference frames in all equations above.
Just like reference points, reference frames need to be well documented.
Transformation from one to another reference frame is possible by matrix multiplication with a transformation matrix.
It turns out that reference frames are not required for the calculations above: one can and should simply stay in the inertial reference frame.

If one, however, decides to venture into the reference frames (as the author did), be aware that ficticious forces add to the balance.
Interested readers may refer to a practical guide by the author citep:Mielke2020wrenches.


** Quaternions
On top of the force/moment complexity comes the issue of quantifying rotation in space.
Angular momentum depends on angular acceleration \(\ddot\theta\), which is a temporal derivative of "angle".
But getting that angle in 3D is not exactly trivial, and there are several complementary notations.


When we think about rotation in space, we might think about an axis and an angle.
And that is a good point to start.

#+begin_center
axis: \(\begin{pmatrix}x\\y\\z \end{pmatrix}\), angle: \(\theta\)
#+end_center

On the swinging door, the axis would be the line through the hinge points, and the angle could be measured as the radians separating open and closed state.
Ideally, one would want to combine axis and angle into a single object \(q\), and it turns out that the following way is convenient:

@@latex:\label{eqn:quaternion}@@
#+begin_center
\[\begin{pmatrix}cos(\theta/2)\\x\cdot sin(\theta/2)\\y\cdot sin(\theta/2)\\z\cdot sin(\theta/2) \end{pmatrix} = q = \begin{pmatrix}q_w\\q_x\\q_y\\q_z \end{pmatrix}\]
#+end_center

There also exists a conjugate, \(q^{-1}\):
#+begin_center
\[q^{-1} = (q_w, -q_x, -q_y, -q_z)\]
#+end_center


And this object allows for convenient spatial rotation, by almost-simple multiplication:
take any 3D point \(P\) with 4D coordinates \(0, a, b, c\):
#+begin_center
\[P_{rot} = q\cdot P\cdot q^{-1}\]
#+end_center

The dot "\(\cdot\)" is just vector multiplication, and computational tools can handle this operation quickly and efficiently.
Better yet, one can stack quaternions by (non-commutatively) multiplying them:
#+begin_center
\[ q_2 \cdot \left( q_1\cdot P\cdot q_1^{-1}\right) \cdot q_2^{-1} = (q_2\cdot q_1) P (q_2\cdot q_1)^{-1} \]
#+end_center

Working with time series of quaternions (\(q(t)\), i.e. the angular position of an object changing over time), there is a formula for getting the angular velocity \(\dot \theta\) from the time differences \(dq/dt\) which fortunately even works with numeric differentials \(\frac{\Delta q}{\Delta t}\) of real measurements citep:Baker1999.
#+begin_center
\[\dot \theta = 2 \frac{\Delta q}{\Delta t} \cdot q^{-1} \]
#+end_center

A quaternion variant for the Kabsch algorithm exists citep:Kabsch1976,Lawrence2019,Kneller1991.
This algorithm is useful to find the rotational difference between rigid bodies, including the change of rotation of a rigid body between two measurement times.


Quaternion operations are usually included as functions in common quaternion toolboxes (for example in [[https://www.mathworks.com/discovery/quaternion.html][matlab]], [[https://cran.r-project.org/web/packages/onion/onion.pdf][R]], and [[https://pypi.org/project/numpy-quaternion][Python]]).
And toolboxes also provide the capability of conversion to other notations of spatial rotation (Euler- or Tait-Bryan angles, Rotation Matrices).
# http://www.euclideanspace.com/physics/kinematics/angularvelocity/QuaternionDifferentiation2.pdf


Just like with wrenches, quaternions cause discomfort to untrained analysts because they seemingly leave the familiar space of 3D geometry.
However, if one simply accepts that maths can handle 4D or 6D problems, the reward is computational convenience.
Superposition and the generation of temporal derivatives are readily available.
Quaternions also avoid some of the pitfalls of the alternative methods (gimbal lock problem, order dependence).
They have an intuitive geometric interpretation through the axis-angle-analogy.
And if anatomically relevant axes are required for communication, they can easily be transformed to such.

This does not imply that inverse dynamic calculations are impossible with Euler Angles.
Yet in most applications, quaternions are mathematically elegant and efficient.


* Dynamics: Application

** Generic Approach
The theoretical considerations above assemble several technical advantages which are worth summarizing.
+ The Balance of Wrenches, equation \eqref{eqn:balance_of_wrenches}, can be calculated entirely in the inertial reference frame, without repeated switch to joint coordinate systems.
+ Wrenches can easily be moved to other reference points via equation \eqref{eqn:shift_wrench}.
+ A convenient point to calculate the balance of wrenches is the center of mass (\(COM\), see below); rotation about that point is an expression of spin angular momentum (an intrinsic property) and some components simplify (e.g. gravitational wrench \(W_{g}\)).
+ Expressing rotational motion by quaternions avoids issues of other methods; favorable features are linear superposition and direct derivative calculation.

These favorable technical properties have not gone unnoticed citep:Dumas2004,Dumas2007.
Dumas et al. (2004) presented a numeric procedure to perform segment-wise balance of wrenches @@latex:\citep[equation 15 in][]{Dumas2004}@@.
This enables the complete solution of inverse dynamic problems with a single, easy to apply numeric formula.
Dumas /et al./ have provided and since improved an implementation of their procedure in Matlab citep:DumasMatlab.


The author of this thesis has reproduced that procedure in python, both numerically and analytically citep:Mielke2021id.


** Algorithm
With wrenches, quaternions, or the numerical formula at hand, one can compute the Balance of Wrenches for a single segment.
Limb segments are usually arranged in a chain, e.g. a human leg consists of the thigh, a lower leg, a foot, and toes.
The issue is that, whereas the inertial wrenches (gravitational wrench, friction, ...) are known, connecting wrenches usually are not.
Each segment (e.g. the thigh) receives a wrench input from all adjacent segments (e.g. the pelvis and the lower leg).
The dynamic wrench of a segment can be measured (e.g. by quantifying movement of the thigh).

There is one exception: the distalmost segment which has ground contact.
Instrumented runways can contain force plates to measure contact forces and moments at the contact of the distal limb on the ground.
Force plates usually generate electronic read-outs from directional, pressure sensitive piezo crystals.
By calibrating the plate, one can convert a voltage profile to forces, moments, and a contact point, all of which are changing over time.


Hence, the practical strategy citep:Robertson2013,Lynch2017,Dumas2004 is to start at the most distal limb segment (e.g. the foot-toe complex), and measure its movement and ground contact wrench.
In that situation, all wrenches in the balance are known, except the wrench at the proximal joint (human foot example: the ankle wrench).
The external wrench at the ground contact point, in the balance calculation of the segment which is in ground contact, is also called the tip wrench; trivially, it is zero if the distal segment is lifted off the ground.
One can calculate the wrench on the proximal joint by subtracting all known external wrenches (ground contact wrench, gravitational wrench, ...; all shifted to the \(COM\)) from the dynamic wrench of the segment (measured linear and angular movement).
The proximal joint wrench, shifted to the joint position and inverted in sign (Newton's \(n^{th}\) law), then becomes the tip wrench when calculating the balance of the proximally adjacent segment (Fig. \ref{fig:wrenchbalance}).

#+CAPTION: Wrench balance of a piglet femur (sketch), as it can be computed for each segment from distal to proximal. The tip wrench (\(W_{tip}\), at the distal joint) is the input from the distal adjacent segment. Dynamic wrench (\(W_{dyn}\), at the center of mass/\(COM\)) is calculated from kinematics (see above). Gravitational wrench (\(W_{g}\), at \(COM\)) is known by the weight of the segment. These wrenches allow to calculate the joint wrench (\(W_{joint}\), at the proximal joint), which is the tip wrench input for the proximal adjacent segment. All calculations can be performed in the inertial coordinate systen (\(ICS\), i.e. the inertial reference frame).
#+LABEL: fig:wrenchbalance
#+ATTR_LATEX: :width 8cm
[[./figures/wrench_balance.pdf]]


** Inertial Properties
The procedure is quite trivial to implement, however the measurement uncertainty for all the involved quantities is not homogeneous.
Whereas force plates and spatial coordinates can be accurately measured in a calibrated lab reference frame, the *inertial properties* of each segment require rough measurements and approximation.
The relevant inertial properties are mass \(m\), center of mass \(COM\), and mass moment of inertia \(I\).
This justifies a closer look at them.


There are several ways to retrieve inertial properties.
The classical method requires a dissection of the segment; this can be a precise anatomical disarticulation or straight-cut slicing of a frozen specimen.
In the case of our slamming door, one would take the door off the hinge.
The segment mass is then measured on a simple scale.
Center of mass could be derived from a classical pendulum experiment (Fig. \ref{fig:door_inertials}): hang an object from a thread, measure oscillation period, apply \(T=2\pi\sqrt{\frac{l}{g}}\) solved for effective length \(l\), repeat the procedure with the object hung along a different axis.
A common simplification is to express the position of the \(COM\) as a fraction of the segment length, inaccurately assuming that it lies on the segment long axis.
Anatomical landmark references are required to transform the relative \(COM\) position into the lab reference frame.
Finally, the classical method to determine mass moment of inertia is by using a trifilar pendulum citep:Schedlinski2001,Korr1962.

The so-retrieved measurements are filled in to the calculations outlined above.


#+CAPTION: Measuring inertial properties of the slamming door: the center of mass.
#+LABEL: fig:door_inertials
#+ATTR_LATEX: :width 6cm
[[./figures/door_inertials.pdf]]


Measurement uncertainty of the inertial properties is not determined by the accuracy of the measurement instruments.
This is where the "slamming door" analogy fails, because a door is actually rigid.
The pendulum methods above yield numerically accurate results.
However, the dissected limb is only a limited representation of the segment /in vivo/, for several reasons.

A first issue is the choice of a disarticulation cutting surface: which mass particles are assigned to which segment?
This choice affects mass, but also COM and mass moment of inertia.

Second, muscles (as a complex composition of fiber bundles and fibers) deform, shift and slide past each other during contraction and movement citep:Bol2013.
Their cross section and fibre distribution can change on non-isometric movements.
Gravity pulls soft tissue into a direction which might be different /in vivo/ and on the preserved configuration of the limb.
Zeugopodial and autopodial segments often include multiple bones which might experience a shift in their relative position during a stride cycle.
All this reduces congruence of the preserved, measured body part and the /in vivo/ situation: mass is constant, yet the COM of a segment is not stable during locomotion, and the mass moment of inertia tensor will most certainly vary during the process.

Third, there might be shrinkage and tissue loss during the preservation of the specimen.
Formol, ethanol, or temperature are typical agents used as a fixative; any fixative has its effect on soft tissue citep:Buytaert2014,Pech1987.
This issue can putatively change all inertials properties of the sample.

Fourth, 3D volumetric imaging (e.g. CT scans) could be an option to replace the measurements above, yet they come with their own set of problems and limitations (e.g. imaging artifacts).


The implications of these conceptual issues will be discussed in detail in the next chapter.
Yet note already that these four effects violate an assumption above: the velocity product terms in the balance of forces are non-negligible because the mass distribution is altered.


* Summary
This chapter serves as a brief overview of the basic methodology of inverse dynamics.
This method exploits the fundamental physical phenomenon of conservation of momentum to model and predict the movement of systems of more or less rigid bodies.
I outlined the general procedure, and documented the specific procedure applicable to inverse dynamic measurements of quadruped, terrestrial locomotion.


In particular, the Wrench-Quaternion method citep:Dumas2004 has proven useful for joining kinematics and force measurements for dynamic calculation.
The reason is computational convenience.
Wrenches are the conceptual link of forces and moments, and they allow convenient computer implementations.
Quaternions have favorable properties to calculate spatial rotation in the context of rigid body motion (superposition, singularity avoidance, transformability).
This establishes the conceptual framework to perform the relevant calculations of the established algorithm, which involves starting at the distal segments where external forces are known (e.g. ground contact) and processing the calculation towards the torso of the animal.


A crucial simplification of that procedure is that we treat body segments of animals as rigid bodies, which they are not.
By /post mortem/ fixation and dissection, or by volumetric digitization, segments can be separated and their inertial properties measured.



* TODO move Flying Femur to a separate chapter
# Once more, this will contain methodological considerations, backed up with actual measurements of (at least a part of) a piglet.
#+TITLE: The "Flying Femur"
#+SUBTITLE: Computed Tomography and the Potential Facilitation of Inverse Dynamic Calculations

* Inertial Properties

#+CAPTION: Inertial properties of a limb segment.
#+LABEL: fig:inertials
#+ATTR_LATEX: :width 8cm
[[./figures/inertial_properties.pdf]]

** Mass

** Center of Mass

** Mass Moment of Inertia
resistance to angular acceleration
Vector formula
Generalized Steiner
Conventional Methods




* Extracting Mass Moment of Inertia from CT Scans
citep:DuPlessis2013,Durston2022

#+begin_comment
% https://doi.org/10.1117/12.2595473
% https://doi.org/10.2214/ajr.143.5.1101
% https://doi.org/10.1016/S0963-8695(97)00020-0
% https://doi.org/10.1093/iob/obad005
#+end_comment


* Results
** Issue 1: Beam Hardening
** Issue 2: Chemical Composition
+ water streaks on the scan
** Issue 3: Marker Artifacts
+ helical scanning

* Discussion
** Which Inertia Component is Relevant?


* Acknowledgements
# Joaquim & VisionLab
tbd.

# \pagebreak
# References
# \bibliographystyle{apalike}
# \bibliography{literature.bib}

#+begin_comment
** COMMENT Reference Frames and Ficticious Forces
 Take home message: Make sure, in this and all that follows, in what reference frame parameters are defined and whether they were transformed.
 # http://mielke-bio.info/falk/posts/11.id_lmx0b_fforces/

 D’Alambert Force, Euler force, Centrifugal force, Coriolis force

 # http://mielke-bio.info/falk/posts/15.id_lmx4_arm/
 After all, this is how physicists formalize fictitious forces: I read that when Léon Foucault observed precession of his pendulum, no responsible external force could be found, but angular momentum of the pendulum changed. Coriolis Force rectified this discrepancy, and because Coriolis force comes with a rotating frame, this was evidence for the rotation of the earth.

 Back to our question. Are there more than the four fictitious forces? Probably no. Remember the “five accelerations” derivation linked in the prequel notebook of this series. That derivation captures all the possible forms of momentum for which we have evidence.


 I have encountered several types of definitions of fictitious forces during my initial attempts.

 The first type is a practical one, which goes along the lines of “fictitious forces arise because an observer who is captured in the rotating frame is blind to the movement of the frame”. Yes, that is a valid description, but a disappointing definition: What else might the observer be blind to? How can we calculate something we are blind for? And why can’t I not always switch perspective in cases where I’m in charge of the data?

 The second type of definition is a technical one: “fictitious forces need to be introduced to make balance equations work in the rotating reference frame”. That is also a valid point, yet it leaves similar questions as above: Which ones do I have to include when? Where do the formulas come from?

 I have hinted at these aspects above. They certainly help to develop an intuition about fictitious forces, but for me they were not satisfactory. You can find these two categories scattered all over the Wikipedia articles about fictitious forces. Despite my rants herein, I’m not disappointed about Wikipedia, it is just sad that this confirmed my prior on that “Encyclopedia”. But I also see myself as a source of the problem: whereas for trained physicists it is often obvious which and how vectors add up, my humble, untrained mind needs some more explicit guidance. [update 2020/09/12] And although I’m using myself in a tautologous way here, those of you who read my first version of the notebook are witness that I could confidently ignore the D’Alambert force without noticing.

 I found a third definition most convincing, yet it is more like a prescription than a definition. It is the one which I found in the workbooks by Frank Owen (five-term acceleration, see references).

     Conceive a position vector to a point on a rigid body as a superimposition of the position vector of the reference frame attachment point (in static frame), and the movement of the point of interest relative to the attachment (in body frame).
     Calculate component-wise time derivatives of that superimposed vector; use product rule, and make sure to incorporate time changes of reference frame basis vectors.
     In the outcome, two acceleration components are intuitive cartesian superimpositions; the others depend on cross products of angular and linear motion parameters. Four of them are irritatingly labelled “fictitious”.
     A corollary rule of thumb for those three: angular motion parameters (ω

 and derivatives) stem from the static frame, whereas linear motion parameters (x

     and derivatives) are best seen in the body frame.

 [update 2020/09/12] Finally, after having finished my work on this series of notebooks, I would like to attempt another definition, which I think captures the inverse dynamics standpoint: Instead of being forces, Fictitious Forces represent a change of the momentum which is not captured by kinematics in the observer’s frame of reference. Instead of writing them on the side of the external forces (of which I think as the cause of a momentum change), I tend to put them on the “effect” side and would rather call them “unbalanced change of momentum” (“unbalanced” as in “not part of the balance”).

 I had to write a couple of notebooks to come to that conclusion, and would be glad if you like to follow through. The fourth one will explain this fourth definition in more detail.

 This preparational notebook has solved some puzzles which I encountered when starting to learn about fictitious forces. Make sure to keep track of your reference frames and reference points. Good (i.e. explicit, structured, well commented) programming style can facilitate this. And remember that, even if you think it is obvious which parameters you took in which transformation, make sure that others can reproduce your line of thought.

 With these tools at our hands, we can advance to elementary examples. I’ll start by isolating Euler, i.e. with an example that should show the Euler force in isolation, in the next notebook. If you don’t mind the explanations, feel free to skip ahead to the code from the application to a general (n-link) limb.


** COMMENT Application: The N-Segment Piglet Limb
# http://mielke-bio.info/falk/posts/16.id_lmx5_nlink


#+end_comment
